"""add core tables

Revision ID: afa06c133ae2
Revises:
Create Date: 2026-08-21 21:59:20.221494

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "afa06c133ae2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("allowed_root_folders", sa.JSON(), nullable=True),
        sa.Column("trash_folder_path", sa.String(), nullable=False),
        sa.Column("filename_pattern", sa.String(), nullable=True),
        sa.Column("filename_pattern_hint", sa.String(), nullable=True),
        sa.Column("ai_endpoint_url", sa.String(), nullable=False),
        sa.Column("ai_model_name", sa.String(), nullable=False),
        sa.Column("ai_api_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("webdav_path", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("scanned_at", sa.DateTime(), nullable=False),
        sa.Column("discovered_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "skipped", "moved", "trashed", "failed", name="documentstatus"),
            nullable=False,
        ),
        sa.Column("skip_count", sa.Integer(), nullable=False),
        sa.Column(
            "proposal_status",
            sa.Enum("pending", "ready", "failed", name="proposalstatus"),
            nullable=False,
        ),
        sa.Column("proposal_error", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_webdav_path"), "document", ["webdav_path"], unique=True)
    op.create_table(
        "history_entry",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("final_filename", sa.String(), nullable=False),
        sa.Column("final_folder_path", sa.String(), nullable=False),
        sa.Column("source_folder_path", sa.String(), nullable=False),
        sa.Column("action", sa.Enum("moved", "trashed", name="historyaction"), nullable=False),
        sa.Column("was_overridden", sa.Boolean(), nullable=False),
        sa.Column("suggestion_snapshot", sa.JSON(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("revertible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_history_entry_document_id"), "history_entry", ["document_id"], unique=False
    )
    op.create_table(
        "proposal",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("suggested_name", sa.String(), nullable=False),
        sa.Column("target_folder_path", sa.String(), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("reasoning_text", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proposal_document_id"), "proposal", ["document_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proposal_document_id"), table_name="proposal")
    op.drop_table("proposal")
    op.drop_index(op.f("ix_history_entry_document_id"), table_name="history_entry")
    op.drop_table("history_entry")
    op.drop_index(op.f("ix_document_webdav_path"), table_name="document")
    op.drop_table("document")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
