import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { StrictMode } from "react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { NavigationGuardProvider, useConfirmNavigation } from "@/hooks/useNavigationGuard";
import type { Settings } from "@/services/api/types";
import SettingsPage from "./SettingsPage";

vi.mock("@/services/api/client", () => ({
  apiClient: {
    getSettings: vi.fn(),
    updateSettings: vi.fn(),
    listAiModels: vi.fn(),
    listAiEndpoints: vi.fn(),
    listAiTasks: vi.fn(),
  },
}));
vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: vi.fn() } }));

import { apiClient } from "@/services/api/client";

/** `noUncheckedIndexedAccess` makes `array[i]` come back `T | undefined` -- this asserts the
 * index actually exists instead of reaching for a non-null assertion. */
function nth<T>(items: T[], index: number): T {
  const item = items[index];
  if (item === undefined) throw new Error(`Expected an element at index ${index}`);
  return item;
}

/** The Save button belonging to one named section, found through the form it sits in.
 * "the last Save button" used to mean AI's, right up until a fourth section was added
 * below it -- which is not what any of these tests were ever trying to say. */
function sectionSave(title: string): HTMLElement {
  const form = screen.getByText(title, { selector: "div" }).closest("form");
  if (form === null) throw new Error(`No form around the '${title}' section.`);
  return within(form).getByRole("button", { name: "Save" });
}

function settings(overrides: Partial<Settings> = {}): Settings {
  return {
    allowed_root_folders: ["/Documents/Finance", "/Documents/Medical"],
    trash_folder_path: "/Documents/.trash",
    filename_pattern: null,
    filename_pattern_hint: null,
    store_ocr_text: true,
    ...overrides,
  };
}

/** A sibling probe inside the same NavigationGuardProvider as SettingsPage, so tests can
 * exercise whether SettingsPage actually armed the guard -- mirroring the pattern in
 * useNavigationGuard.test.tsx. */
function NavProbe() {
  const confirmNavigation = useConfirmNavigation();
  return (
    <button type="button" onClick={() => confirmNavigation()}>
      leave
    </button>
  );
}

function renderPage() {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <NavigationGuardProvider>
          <SettingsPage />
          <NavProbe />
        </NavigationGuardProvider>
      </QueryClientProvider>
    </StrictMode>,
  );
  return { queryClient };
}

/** Renders and waits for Folders to be interactive. `useFieldArray`'s ids are regenerated by
 * StrictMode's synthetic mount-effects-cleanup-remount cycle (real React 18 dev behavior,
 * invisible to an actual user -- it settles within the same browser task, well before a human
 * could click). In jsdom, `findByLabelText` can resolve to the pre-settle node, and userEvent's
 * `.clear()`/`.type()` then fail with "could not be focused" because that node gets torn down
 * a tick later. Waiting one extra macrotask after the first match appears lets it settle before
 * any test touches the DOM. */
async function renderReadyPage() {
  const result = renderPage();
  await screen.findByLabelText("Allowed root folder 1");
  await act(async () => {
    await new Promise((resolve) => setTimeout(resolve, 0));
  });
  return result;
}

describe("SettingsPage", () => {
  beforeEach(() => {
    // The AI cards render on every one of these tests; they have their own suites.
    vi.mocked(apiClient.listAiEndpoints).mockResolvedValue([]);
    vi.mocked(apiClient.listAiTasks).mockResolvedValue([
      { task: "extraction", steps: [] },
      { task: "filing", steps: [] },
    ]);
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.clearAllMocks();
  });

  it("shows a loading skeleton before settings resolve", () => {
    vi.mocked(apiClient.getSettings).mockReturnValue(new Promise(() => {}));
    renderPage();

    expect(screen.getByRole("heading", { name: "Settings" })).toBeInTheDocument();
    expect(screen.getAllByText("", { selector: "[aria-busy]" }).length).toBeGreaterThan(0);
  });

  it("shows an error card with retry on failure", async () => {
    vi.mocked(apiClient.getSettings).mockRejectedValueOnce(new Error("boom"));
    renderPage();

    expect(await screen.findByText(/couldn't load settings/i)).toBeInTheDocument();
    const retry = screen.getByRole("button", { name: /try again/i });

    vi.mocked(apiClient.getSettings).mockResolvedValueOnce(settings());
    await userEvent.setup().click(retry);

    expect(await screen.findByDisplayValue("/Documents/Finance")).toBeInTheDocument();
  });

  it("renders every section once settings load", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    renderPage();

    // SectionCard's title is a styled div, not a semantic heading (shadcn's CardTitle).
    expect(await screen.findByText("Folders")).toBeInTheDocument();
    expect(screen.getByText("Naming")).toBeInTheDocument();
    expect(screen.getByText("AI endpoints")).toBeInTheDocument();
    expect(await screen.findByText("Extraction — read the pages")).toBeInTheDocument();
    expect(screen.getByText("Filing — choose the filename")).toBeInTheDocument();
    expect(screen.getByText("OCR")).toBeInTheDocument();
  });

  it("turns the searchable-copy setting off and saves it", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const toggle = screen.getByLabelText("File a searchable copy of scans");
    expect(toggle).toBeChecked();

    vi.mocked(apiClient.updateSettings).mockResolvedValue(settings({ store_ocr_text: false }));
    await user.click(toggle);
    await user.click(sectionSave("OCR"));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    const payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).toMatchObject({ store_ocr_text: false });
    // The rest of the settings ride along untouched -- every section PUTs the whole object,
    // so a section that dropped a field it does not own would silently clear it.
    expect(payload).toMatchObject({
      allowed_root_folders: ["/Documents/Finance", "/Documents/Medical"],
      trash_folder_path: "/Documents/.trash",
    });
  });

  it("saves Folders and clears dirty state so Save disables again", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");

    const foldersSave = nth(screen.getAllByRole("button", { name: "Save" }), 0);
    expect(foldersSave).toBeEnabled();

    vi.mocked(apiClient.updateSettings).mockResolvedValue(
      settings({ allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"] }),
    );
    await user.click(foldersSave);

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    const payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).toMatchObject({
      allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"],
      trash_folder_path: "/Documents/.trash",
    });
    await waitFor(() =>
      expect(nth(screen.getAllByRole("button", { name: "Save" }), 0)).toBeDisabled(),
    );
  });

  it("keeps a different section's unsaved edits intact when another section saves", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const patternInput = screen.getByLabelText("Filename pattern");
    // userEvent.type() treats { as special key syntax -- {{ escapes to a literal brace.
    // `}` needs no escaping (it's only special inside an active {...} sequence).
    await user.type(patternInput, "^\\d{{4}");

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");

    vi.mocked(apiClient.updateSettings).mockResolvedValue(
      settings({ allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"] }),
    );
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 0));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());

    // Naming's typed text survives the Folders save, and Naming is still dirty.
    expect(patternInput).toHaveValue("^\\d{4}");
    // Folders is clean (disabled) again; Naming is the remaining enabled Save.
    const enabledSaves = screen
      .getAllByRole("button", { name: "Save" })
      .filter((b) => !b.hasAttribute("disabled"));
    expect(enabledSaves).toHaveLength(1);
  });

  it("shows a live validation error for an invalid regex as the user types", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const patternInput = screen.getByLabelText("Filename pattern");
    await user.type(patternInput, "(unclosed");

    expect(await screen.findByText("Not a valid regular expression.")).toBeInTheDocument();

    // Save is gated on isDirty, not isValid (a real submit step should still surface the
    // error rather than silently disabling the button) -- so it stays clickable, but zod's
    // resolver blocks the actual submit from reaching updateSettings.
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 1));
    expect(apiClient.updateSettings).not.toHaveBeenCalled();
  });

  it("normalizes an empty filename pattern to null, not an empty string", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings({ filename_pattern: "^\\d{4}" }));
    const user = userEvent.setup();
    await renderReadyPage();

    const patternInput = screen.getByLabelText("Filename pattern");
    await user.clear(patternInput);

    vi.mocked(apiClient.updateSettings).mockResolvedValue(settings({ filename_pattern: null }));
    // Naming is the second section rendered.
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 1));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    const payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).toMatchObject({ filename_pattern: null });
  });

  it("flags a duplicate allowed root under the offending row", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Medical");
    // Folders validates on submit, not per-field (no `mode: "onChange"`) -- attempt a save.
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 0));

    expect(await screen.findByText("Duplicate folder.")).toBeInTheDocument();
    expect(apiClient.updateSettings).not.toHaveBeenCalled();
  });

  it("arms the navigation guard once any section is dirty, and disarms after a successful save", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const confirmSpy = vi.spyOn(window, "confirm").mockReturnValue(false);
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");

    await user.click(screen.getByRole("button", { name: "leave" }));
    expect(confirmSpy).toHaveBeenCalled();

    confirmSpy.mockClear();
    vi.mocked(apiClient.updateSettings).mockResolvedValue(
      settings({ allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"] }),
    );
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 0));
    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());

    await user.click(screen.getByRole("button", { name: "leave" }));
    expect(confirmSpy).not.toHaveBeenCalled();
  });

  it("discards edits back to the last-saved values", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");
    expect(firstRoot).toHaveValue("/Documents/Legal");

    await user.click(nth(screen.getAllByRole("button", { name: "Discard changes" }), 0));

    // Resetting a useFieldArray-backed form re-seeds fresh row ids, so the row's DOM node
    // is a new element -- re-query rather than trust the pre-discard reference.
    expect(screen.getByLabelText("Allowed root folder 1")).toHaveValue("/Documents/Finance");
    expect(apiClient.updateSettings).not.toHaveBeenCalled();

    // Same `{ keepDirtyValues: false }` fix, but on a plain register()'d field rather than
    // a useFieldArray row -- confirms the fix isn't specific to the field-array case it was
    // originally caught through.
    const hintInput = screen.getByLabelText("Pattern hint");
    await user.type(hintInput, " extra text");
    await user.click(nth(screen.getAllByRole("button", { name: "Discard changes" }), 1));
    expect(hintInput).toHaveValue("");
  });
});
