import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { StrictMode } from "react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { NavigationGuardProvider, useConfirmNavigation } from "@/hooks/useNavigationGuard";
import { ApiError } from "@/services/api/errors";
import type { Settings } from "@/services/api/types";
import SettingsPage from "./SettingsPage";

vi.mock("@/services/api/client", () => ({
  apiClient: { getSettings: vi.fn(), updateSettings: vi.fn(), listAiModels: vi.fn() },
}));
vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: vi.fn() } }));

import { apiClient } from "@/services/api/client";

/** `noUncheckedIndexedAccess` makes `array[i]` come back `T | undefined` -- this asserts the
 * index actually exists instead of reaching for a non-null assertion. */
function nth<T>(items: T[], index: number): T {
  const item = items[index];
  if (item === undefined) throw new Error(`Expected an element at index ${index}`);
  return item;
}

function settings(overrides: Partial<Settings> = {}): Settings {
  return {
    allowed_root_folders: ["/Documents/Finance", "/Documents/Medical"],
    trash_folder_path: "/Documents/.trash",
    filename_pattern: null,
    filename_pattern_hint: null,
    ai_endpoint_url: "https://ollama.local:11434",
    ai_model_name: "llama3",
    ai_api_key_set: true,
    ...overrides,
  };
}

/** A sibling probe inside the same NavigationGuardProvider as SettingsPage, so tests can
 * exercise whether SettingsPage actually armed the guard -- mirroring the pattern in
 * useNavigationGuard.test.tsx. */
function NavProbe() {
  const confirmNavigation = useConfirmNavigation();
  return (
    <button type="button" onClick={() => confirmNavigation()}>
      leave
    </button>
  );
}

function renderPage() {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <NavigationGuardProvider>
          <SettingsPage />
          <NavProbe />
        </NavigationGuardProvider>
      </QueryClientProvider>
    </StrictMode>,
  );
  return { queryClient };
}

/** Renders and waits for Folders to be interactive. `useFieldArray`'s ids are regenerated by
 * StrictMode's synthetic mount-effects-cleanup-remount cycle (real React 18 dev behavior,
 * invisible to an actual user -- it settles within the same browser task, well before a human
 * could click). In jsdom, `findByLabelText` can resolve to the pre-settle node, and userEvent's
 * `.clear()`/`.type()` then fail with "could not be focused" because that node gets torn down
 * a tick later. Waiting one extra macrotask after the first match appears lets it settle before
 * any test touches the DOM. */
async function renderReadyPage() {
  const result = renderPage();
  await screen.findByLabelText("Allowed root folder 1");
  await act(async () => {
    await new Promise((resolve) => setTimeout(resolve, 0));
  });
  return result;
}

describe("SettingsPage", () => {
  afterEach(() => {
    vi.restoreAllMocks();
    vi.clearAllMocks();
  });

  it("shows a loading skeleton before settings resolve", () => {
    vi.mocked(apiClient.getSettings).mockReturnValue(new Promise(() => {}));
    renderPage();

    expect(screen.getByRole("heading", { name: "Settings" })).toBeInTheDocument();
    expect(screen.getAllByText("", { selector: "[aria-busy]" }).length).toBeGreaterThan(0);
  });

  it("shows an error card with retry on failure", async () => {
    vi.mocked(apiClient.getSettings).mockRejectedValueOnce(new Error("boom"));
    renderPage();

    expect(await screen.findByText(/couldn't load settings/i)).toBeInTheDocument();
    const retry = screen.getByRole("button", { name: /try again/i });

    vi.mocked(apiClient.getSettings).mockResolvedValueOnce(settings());
    await userEvent.setup().click(retry);

    expect(await screen.findByDisplayValue("/Documents/Finance")).toBeInTheDocument();
  });

  it("renders all three sections once settings load", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    renderPage();

    // SectionCard's title is a styled div, not a semantic heading (shadcn's CardTitle).
    expect(await screen.findByText("Folders")).toBeInTheDocument();
    expect(screen.getByText("Naming")).toBeInTheDocument();
    expect(screen.getByText("AI")).toBeInTheDocument();
  });

  it("saves Folders and clears dirty state so Save disables again", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");

    const foldersSave = nth(screen.getAllByRole("button", { name: "Save" }), 0);
    expect(foldersSave).toBeEnabled();

    vi.mocked(apiClient.updateSettings).mockResolvedValue(
      settings({ allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"] }),
    );
    await user.click(foldersSave);

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    const payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).toMatchObject({
      allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"],
      trash_folder_path: "/Documents/.trash",
    });
    // ai_api_key_set must never leak into the update payload -- it isn't part of
    // SettingsUpdate and the backend only ignores it by convention (CLAUDE.md rule 5).
    expect(payload).not.toHaveProperty("ai_api_key_set");

    await waitFor(() =>
      expect(nth(screen.getAllByRole("button", { name: "Save" }), 0)).toBeDisabled(),
    );
  });

  it("keeps a different section's unsaved edits intact when another section saves", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const patternInput = screen.getByLabelText("Filename pattern");
    // userEvent.type() treats { as special key syntax -- {{ escapes to a literal brace.
    // `}` needs no escaping (it's only special inside an active {...} sequence).
    await user.type(patternInput, "^\\d{{4}");

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");

    vi.mocked(apiClient.updateSettings).mockResolvedValue(
      settings({ allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"] }),
    );
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 0));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());

    // Naming's typed text survives the Folders save, and Naming is still dirty.
    expect(patternInput).toHaveValue("^\\d{4}");
    // Folders is clean (disabled) again; Naming is the remaining enabled Save.
    const enabledSaves = screen
      .getAllByRole("button", { name: "Save" })
      .filter((b) => !b.hasAttribute("disabled"));
    expect(enabledSaves).toHaveLength(1);
  });

  it("shows a live validation error for an invalid regex as the user types", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const patternInput = screen.getByLabelText("Filename pattern");
    await user.type(patternInput, "(unclosed");

    expect(await screen.findByText("Not a valid regular expression.")).toBeInTheDocument();

    // Save is gated on isDirty, not isValid (a real submit step should still surface the
    // error rather than silently disabling the button) -- so it stays clickable, but zod's
    // resolver blocks the actual submit from reaching updateSettings.
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 1));
    expect(apiClient.updateSettings).not.toHaveBeenCalled();
  });

  it("normalizes an empty filename pattern to null, not an empty string", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings({ filename_pattern: "^\\d{4}" }));
    const user = userEvent.setup();
    await renderReadyPage();

    const patternInput = screen.getByLabelText("Filename pattern");
    await user.clear(patternInput);

    vi.mocked(apiClient.updateSettings).mockResolvedValue(settings({ filename_pattern: null }));
    // Naming is the second section rendered.
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 1));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    const payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).toMatchObject({ filename_pattern: null });
  });

  it("flags a duplicate allowed root under the offending row", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Medical");
    // Folders validates on submit, not per-field (no `mode: "onChange"`) -- attempt a save.
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 0));

    expect(await screen.findByText("Duplicate folder.")).toBeInTheDocument();
    expect(apiClient.updateSettings).not.toHaveBeenCalled();
  });

  it("omits the API key from the save payload when left blank, and includes it when typed", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const modelInput = screen.getByLabelText("Model");
    await user.clear(modelInput);
    await user.type(modelInput, "llama3.1");

    vi.mocked(apiClient.updateSettings).mockResolvedValue(settings({ ai_model_name: "llama3.1" }));
    // AI is the last section rendered, so its Save button is the last one in document order.
    const aiSaveButtons = screen.getAllByRole("button", { name: "Save" });
    await user.click(nth(aiSaveButtons, aiSaveButtons.length - 1));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    let payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).not.toHaveProperty("ai_api_key");

    vi.mocked(apiClient.updateSettings).mockClear();
    const keyInput = screen.getByLabelText("API key");
    await user.type(keyInput, "sk-secret-value");
    vi.mocked(apiClient.updateSettings).mockResolvedValue(settings());
    const aiSaveButtonsAfterKey = screen.getAllByRole("button", { name: "Save" });
    await user.click(nth(aiSaveButtonsAfterKey, aiSaveButtonsAfterKey.length - 1));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    payload = vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0];
    expect(payload).toMatchObject({ ai_api_key: "sk-secret-value" });

    // The key never lands in the query cache: Settings has no ai_api_key field, and the
    // field itself is cleared back to blank after a successful save (CLAUDE.md rule 5).
    await waitFor(() => expect(keyInput).toHaveValue(""));
    expect(JSON.stringify(window.localStorage)).not.toContain("sk-secret-value");
  });

  it("tests the endpoint currently typed in the form and offers its models in a dropdown", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    vi.mocked(apiClient.listAiModels).mockResolvedValue({ models: ["llama3", "qwen3"] });
    const user = userEvent.setup();
    await renderReadyPage();

    // Typed, not saved: finding out the URL is wrong is the reason to press Test.
    const endpoint = screen.getByLabelText("Endpoint URL");
    await user.clear(endpoint);
    await user.type(endpoint, "https://api.infomaniak.com/2/ai/1/openai/v1");
    await user.click(screen.getByRole("button", { name: /test connection/i }));

    await waitFor(() => expect(apiClient.listAiModels).toHaveBeenCalled());
    expect(vi.mocked(apiClient.listAiModels).mock.calls[0]?.[0]).toEqual({
      ai_endpoint_url: "https://api.infomaniak.com/2/ai/1/openai/v1",
    });

    expect(await screen.findByText("2 models offered by this endpoint.")).toBeInTheDocument();
    const picker = await screen.findByRole("combobox", { name: "Model" });
    expect(picker).toHaveTextContent("llama3");
  });

  it("sends the typed API key with the test, and falls back to the stored one when blank", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    vi.mocked(apiClient.listAiModels).mockResolvedValue({ models: [] });
    const user = userEvent.setup();
    await renderReadyPage();

    await user.type(screen.getByLabelText("API key"), "sk-typed");
    await user.click(screen.getByRole("button", { name: /test connection/i }));

    await waitFor(() => expect(apiClient.listAiModels).toHaveBeenCalled());
    expect(vi.mocked(apiClient.listAiModels).mock.calls[0]?.[0]).toMatchObject({
      ai_api_key: "sk-typed",
    });
    // An endpoint that answers with nothing is not a picker -- the field stays typeable.
    expect(await screen.findByText(/listed no models/i)).toBeInTheDocument();
    expect(screen.getByLabelText("Model")).toHaveValue("llama3");
  });

  it("shows why the test failed and leaves the model as a text field", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    vi.mocked(apiClient.listAiModels).mockRejectedValue(
      new ApiError("ai_unavailable", "The AI endpoint returned 404 for .../models.", 503),
    );
    const user = userEvent.setup();
    await renderReadyPage();

    await user.click(screen.getByRole("button", { name: /test connection/i }));

    expect(
      await screen.findByText("The AI endpoint returned 404 for .../models."),
    ).toBeInTheDocument();
    expect(screen.getByLabelText("Model")).toHaveValue("llama3");
  });

  it("picks a model from the dropdown, which dirties the form and saves that model", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    vi.mocked(apiClient.listAiModels).mockResolvedValue({ models: ["llama3", "qwen3"] });
    const user = userEvent.setup();
    await renderReadyPage();

    await user.click(screen.getByRole("button", { name: /test connection/i }));
    const picker = await screen.findByRole("combobox", { name: "Model" });
    await user.click(picker);
    await user.click(await screen.findByRole("option", { name: "qwen3" }));

    vi.mocked(apiClient.updateSettings).mockResolvedValue(settings({ ai_model_name: "qwen3" }));
    const saveButtons = screen.getAllByRole("button", { name: "Save" });
    await user.click(nth(saveButtons, saveButtons.length - 1));

    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());
    expect(vi.mocked(apiClient.updateSettings).mock.calls[0]?.[0]).toMatchObject({
      ai_model_name: "qwen3",
    });
  });

  it("can fall back to typing a model name the endpoint does not list", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    vi.mocked(apiClient.listAiModels).mockResolvedValue({ models: ["llama3", "qwen3"] });
    const user = userEvent.setup();
    await renderReadyPage();

    await user.click(screen.getByRole("button", { name: /test connection/i }));
    await screen.findByRole("combobox", { name: "Model" });

    await user.click(screen.getByRole("button", { name: /enter a model name manually/i }));

    const modelInput = screen.getByLabelText("Model");
    expect(modelInput).toHaveValue("llama3");
    await user.clear(modelInput);
    await user.type(modelInput, "custom/model");
    expect(modelInput).toHaveValue("custom/model");
  });

  it("arms the navigation guard once any section is dirty, and disarms after a successful save", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const confirmSpy = vi.spyOn(window, "confirm").mockReturnValue(false);
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");

    await user.click(screen.getByRole("button", { name: "leave" }));
    expect(confirmSpy).toHaveBeenCalled();

    confirmSpy.mockClear();
    vi.mocked(apiClient.updateSettings).mockResolvedValue(
      settings({ allowed_root_folders: ["/Documents/Legal", "/Documents/Medical"] }),
    );
    await user.click(nth(screen.getAllByRole("button", { name: "Save" }), 0));
    await waitFor(() => expect(apiClient.updateSettings).toHaveBeenCalled());

    await user.click(screen.getByRole("button", { name: "leave" }));
    expect(confirmSpy).not.toHaveBeenCalled();
  });

  it("discards edits back to the last-saved values", async () => {
    vi.mocked(apiClient.getSettings).mockResolvedValue(settings());
    const user = userEvent.setup();
    await renderReadyPage();

    const firstRoot = screen.getByLabelText("Allowed root folder 1");
    await user.clear(firstRoot);
    await user.type(firstRoot, "/Documents/Legal");
    expect(firstRoot).toHaveValue("/Documents/Legal");

    await user.click(nth(screen.getAllByRole("button", { name: "Discard changes" }), 0));

    // Resetting a useFieldArray-backed form re-seeds fresh row ids, so the row's DOM node
    // is a new element -- re-query rather than trust the pre-discard reference.
    expect(screen.getByLabelText("Allowed root folder 1")).toHaveValue("/Documents/Finance");
    expect(apiClient.updateSettings).not.toHaveBeenCalled();

    // Same `{ keepDirtyValues: false }` fix, but on a plain register()'d field rather than
    // a useFieldArray row -- confirms the fix isn't specific to the field-array case it was
    // originally caught through.
    const hintInput = screen.getByLabelText("Pattern hint");
    await user.type(hintInput, " extra text");
    await user.click(nth(screen.getAllByRole("button", { name: "Discard changes" }), 1));
    expect(hintInput).toHaveValue("");
  });
});
